language: python

python:
  - 2.7

addons:
  apt:
    packages:
      - rsync
      - openssh-client
      - openssh-server

install:
  - rsync -v
  - ssh -v
  - ls ${HOME}/.ssh
  - service ssh status
  - ssh-keygen -t rsa -N "" -f ${HOME}/.ssh/id_rsa
  - cat ${HOME}/.ssh/id_rsa.pub >> ${HOME}/.ssh/authorized_keys

script:
  - echo "tst"
