language: python

os:
  - linux

before_script:
  - lsb_release -a
  - ping -c1 localhost
  - ssh -vv localhost 'echo test'
  - rsync -aPvv /usr/include localhost:/tmp/

python:
  - 2.7

addons:
  apt:
    packages:
      - rsync
      - openssh-client
      - openssh-server

install:
  - rsync --version
  - ssh -V
  - ls -la ${HOME}/.ssh
  - service ssh status
  - ssh-keygen -t rsa -N "" -f ${HOME}/.ssh/id_rsa
  - cat ${HOME}/.ssh/id_rsa.pub >> ${HOME}/.ssh/authorized_keys

script:
  - echo "tst"
